### ISSUE TITLE
.so

### ISSUE THREAD

**Issue by binbin0617** [LongAgoLong/QrcodeDemo#1]

**Comment by binbin0617** [comment]
您好 我需要一个armeabi这个文件夹下的libzbar.so文件 ，能麻烦您提供一下吗？

**Comment by LongAgoLong** [comment]
@binbin0617 用armeabi-v7a的就可以了，新版的ndk编译已经不支持armeabi了，把armeabi-v7a的copy到armeabi目录就可以了

**Comment by binbin0617** [comment]
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.szht.htappfuture.utils.ZbarDecode.decode(byte[], int, int, boolean, int, int, int, int) (tried Java_com_szht_htappfuture_utils_ZbarDecode_decode and Java_com_szht_htappfuture_utils_ZbarDecode_decode___3BIIZIIII)
        at com.szht.htappfuture.utils.ZbarDecode.decode(Native Method)
        at com.szht.htappfuture.utils.ZbarDecodeUtil.decode(ZbarDecodeUtil.java:21)
        at com.szht.htappfuture.utils.ZbarDecodeUtil.decode(ZbarDecodeUtil.java:41)
        at com.szht.htappfuture.main.MainAty$12.resultFilesSucceed(MainAty.java:703)
        at utils.task.CompressImageTask$3$1.run(CompressImageTask.java:250)

我之前拷贝的就是这个下面的.so文件，不过报了这个错误，是因为ZbarDecode这个类跟你的包名不一样吗？我直接把类拷贝到我的项目中的，没拷贝整个moudle

**Comment by binbin0617** [comment]
谢谢您 我解决掉了
